# frozen_string_literal: true

source "https://rubygems.org" do
    gem "headless", "~>2.3.1"
    gem "watir", '~>6.16' 
end

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
